# Generated by Django 6.0.4 on 2026-04-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('Premier', 'Premier'), ('Competitive', 'Competitive')], default='Premier', max_length=24)),
                ('team_score', models.PositiveSmallIntegerField()),
                ('opponent_score', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in minutes')),
                ('played_at', models.DateTimeField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveSmallIntegerField(default=0)),
                ('deaths', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('headshots', models.PositiveSmallIntegerField(default=0)),
                ('mvp_rounds', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='RoundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('round_result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss')], max_length=12)),
                ('kills', models.PositiveSmallIntegerField(default=0)),
                ('headshots', models.PositiveSmallIntegerField(default=0)),
                ('survived', models.BooleanField(default=False)),
                ('mvp', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='matches.match')),
            ],
            options={
                'ordering': ('round_number',),
                'unique_together': {('match', 'round_number')},
            },
        ),
    ]
